### ISSUE TITLE
What's the strategy for this plugin?

### ISSUE THREAD

**Issue by ChasKane** [Ledaryy/obsidian-todoist-completed-tasks#1]
Is the goal of this plugin to render completed todoist tasks?

The existing todoist obsidian plugins don't let you render completed tasks since they rely on todoist filters and [filters don't include completed tasks](https://todoist.com/help/articles/introduction-to-filters). I found a [script on reddit](https://www.reddit.com/r/ObsidianMD/comments/u560vi/comment/i59rikl/) that claims to do the job but the code looks hacky (not a criticism, just that it's prone to break if Todoist changes). I haven't tried it yet but will lyk how it goes if you're interested.

Do you have an alternate idea on how to render completed todoist tasks in obsidian?

**Comment by Ledaryy** [comment]
Hi ChasKane, thanks for reaching out
Yeah, filters do not support completed tasks. My approach will be to fetch everything from sync API (I'm still making research on it, but I think it is possible)
https://developer.todoist.com/sync/v8/#get-all-completed-items
Then, using the date (which the user should input) it will render the completed tasks into the obsidian page
You're welcome to share any ideas/contribute
