### ISSUE TITLE
Feature Request: Allow date range to be specified for templates

### ISSUE THREAD

**Issue by ddeighton** [Ledaryy/obsidian-todoist-completed-tasks#11]
This is related to #3.

I use templates extensively in Obsidian. Is it possible to add a date range in a template and have the plugin pull completed tasks from that range? Perhaps the dates could be added to the `Start line detector` or `End line detector`. 

It would be useful for me. 

Thanks!

**Comment by Ledaryy** [comment]
Hi @ddeighton,
I think it is can be easily implemented. Something like special tags in the "Start line detector" will work for you?
Example: %% COMPLETED_TODOIST_TASKS_START $startDate[2022-09-20] $endDate[2022-09-24] %%
But it would still require pressing the fetch button or calling a command from the obsidian command line.

**Comment by ddeighton** [comment]
I think that would work very well. I could use a template to fill in the dates. This will be helpful for when I forget to fetch the tasks in my daily note, which I fully expect to do at some point. Thanks!

**Comment by djensen47** [comment]
Why not use a dialog box for everything in addition to the special tags? Personally, I only need to import once a day so a dialog box with options to select the project and date range would be fantastic.

**Comment by Ledaryy** [comment]
@djensen47 Sounds good to me. I think you can create a new feature request for it. And then we can discuss and decide if that is worth implementing.
