### ISSUE TITLE
Feature Request: Option to append a string when fetching completed tasks

### ISSUE THREAD

**Issue by ddeighton** [Ledaryy/obsidian-todoist-completed-tasks#13]
I would like to append a string to the end of completed items. In my case, I would like to add a string with `✅` followed by the completion date so that completed tasks are compatible with the [Tasks](https://github.com/obsidian-tasks-group/obsidian-tasks) plugin. This way I can have Todoist completed items show up in Tasks searches.

An example of the string that I'd like to append:
```
✅ 2022-10-17
```

Thanks in advance for any consideration of this request.

**Comment by Ledaryy** [comment]
Hi @ddeighton,
Thanks for using the plugin. 
So, we already have a Prefix, its time to have a Postfix as well :)
I think overall it will not be difficult to implement. I'll reach out to you if I'll have any questions.

**Comment by ricir** [comment]
Dear @Ledaryy , My request is similar, but I would like to have the time of completion added (instead or in addition). Actually. it is very useful to see the list of completed tasks inside my Journal page. Having the time too, would be perfect to understand the progress of the day. Thanks.

**Comment by Ledaryy** [comment]
Hey, @ricir thanks for the proposal!
I've made it possible to specify either you want {current_date} or {task_finish_date} or even both :)

**Comment by ddeighton** [comment]
Thanks for adding this feature. I'm having an issue with the dates. The single digits are not zero-padded. For example, today I am getting "2022-12-9" instead of "2022-12-09". This causes the tasks to be incompatible with the Tasks plugin. Can this be corrected or made as a configurable option?

**Comment by Ledaryy** [comment]
Hey @ddeighton,

Thanks for sharing this. It was just a bug, I've already fixed it and published the new release. About making the dates configurable, it is doable, but I'm not sure if it will be useful. If you think so, feel free to open a new issue with a feature proposal. 
Also, in case you'll find any other bugs, please open new issues instead of posting in this thread, because they can get lost as this thread is marked as completed now.

Enjoy the plugin!

**Comment by ddeighton** [comment]
Thanks! It's working very well now.

**Comment by ricir** [comment]
> Hey, @ricir thanks for the proposal! I've made it possible to specify either you want {current_date} or {task_finish_date} or even both :)

Thank you, fantastic!!!
