### ISSUE TITLE
Render tasks as completed checkboxes

### ISSUE THREAD

**Issue by anvimea** [Ledaryy/obsidian-todoist-completed-tasks#2]
Hi,

Enjoying this plugin quite a bit, but wondering if it would be possible to import Todoist tasks as completed checkboxes, not just in a list format.

It isn't too difficult to manually turn them into checkboxes and mark them as completed, of course. But just wondering if it's possible.

**Comment by Ledaryy** [comment]
Hi Anvimea,

I'm really glad that you enjoying the plugin.
Yes, this feature is on my list. I plan to add it to the next release!
