### ISSUE TITLE
Bug - Does not refresh completed task list

### ISSUE THREAD

**Issue by Naesue** [Ledaryy/obsidian-todoist-completed-tasks#21]
The plugin works fine on a new note in Obsidian.

When I refresh the completed task list for a certain date, the plugin successfully finds the new completed task (here, 5). 
But the task list does not refresh, and there is only 4 here, yet 5 are found.

<img width="801" alt="Capture d’écran 2022-12-09 à 22 36 52" src="https://user-images.githubusercontent.com/100245676/206800028-affcf760-433e-4c32-a101-313d3d8d813e.png">
Edit mode

<img width="1157" alt="Capture d’écran 2022-12-09 à 22 34 13" src="https://user-images.githubusercontent.com/100245676/206799683-c926005b-a20c-4655-afc6-7513bbf49836.png">
Fetching data

---

Operating system: Mac OS Big Sur 11.4
Obsidian: 1.0.3

(Great plugin btw.)

**Comment by Naesue** [comment]
Note: Just found out I only have this issue in preview mode, not in edit mode. 
So I assume the list can't be updated on preview mode. Would be cool to update the list on preview mode but not sure it is doable.

**Comment by Ledaryy** [comment]
Hey @Naesue,
Thanks for using the plugin!

You are absolutely correct in your assumptions! Obsidian allows editing the file only in edit mode. And this plugin operates with the same API as the user does (typing on a keyboard and using the plugin to populate the note with tasks are looks exactly the same from obsidian's perspective). So, unfortunately, it is not possible to edit the note in "preview" mode.

Hope that answers your question. Does not hesitate to reach out in the future if you'll have any questions!

**Comment by Naesue** [comment]
Ah, that makes sense! Tested this out a bit more and it a lot of plugins do operate this way indeed.
It does answer my question! Thank you for your reply.
