### ISSUE TITLE
{task_finish_date} rendering "Not completed yet" on completed tasks

### ISSUE THREAD

**Issue by aventuraviper** [Ledaryy/obsidian-todoist-completed-tasks#22]
Hi,

I was trying to set the plugin up to be compatible with Obsidian Tasks using the example given in the settings menu, but I am having the odd behaviour that the completed tasks found by the plugin are rendering as "Not completed yet" when using the "{task_finish_date}" code.

I am running Obsidian 1.0.3 and plugin version 1.4.2

![image](https://user-images.githubusercontent.com/55485055/208092068-3900db66-1ea7-44e3-8fd8-3441a70a63e0.png)
![image](https://user-images.githubusercontent.com/55485055/208092114-3e9c2918-6618-4397-b210-a3340f1d08b9.png)

**Comment by Ledaryy** [comment]
Hi @aventuraviper,
I just recently discovered this "buggy" behaviour as well. It happened to me when I completed tasks on the mobile app and then tried to render the completed tasks in Obsidian. (It is inconsistent, sometimes works, sometimes not)

Some info on how it works on the plugin side:
The plugin tries to extract "completed_date" from the task JSON that we fetch from the Todoist API.
If there is a date it will render the date. If this entry is empty, it will render "Not completed yet".

So, as you can see, unfortunately, there isn't much we can do about this. So, I just renamed "Not completed yet" to "N/A". And added a note on the settings page: "Note: Todoist API does not always provide a task finish date, 'N/A' will be used in this case."
Hope it will make it less confusing.

Probably later this week I'll try to raise a ticket on Todoist for this. Let's see how it goes.

**Comment by aventuraviper** [comment]
Wow, that was a quick response! Thank you @Ledaryy.

I'm not a developer etc. but is this running the REST or SYNC API? I assume SYNC because completed_at is not part of the REST API, which means that it should always be filled in given the v9 spec doesn't list it as optional in the response? Also, it makes no sense for the task to be registered and appear as completed if there is no completed date! Definitely an odd one and hopefully Todoist can look into it.

Thanks

**Comment by aventuraviper** [comment]
Hi @Ledaryy,

I think I know what is going on and it isn't a Todoist Bug if I'm right. I think the completed_date isn't filled in when you check off a recurring task. Todoist [logs a completion but changes the due date](https://todoist.com/help/articles/can-i-reset-sub-tasks). completed_date is only filled for recurring tasks if you check it off via the menu option "complete forever".

Perhaps you could consider adding some extra logic to the plugin for cases where Todoist returns "Not Completed". For example, if triggered via "Fetch Today's completed Tasks" the plugin should append today's date, if using a specified range maybe the plugin has to ask for user input to decide an a date for all "not completed" tasks unless the range spans just one day (e.g. I use a block from 00:00 to 23:59 in daily notes).

**Comment by Ledaryy** [comment]
Hey @aventuraviper,

You were absolutely correct! The completed date field is empty only for recurring tasks, it works OK for normal tasks.
So I just attached some logic that merges date info from other APIs and it works fine now. 

Thanks a lot for helping identify this issue!

The new version has already been released!

**Comment by aventuraviper** [comment]
> Hey @aventuraviper,
> 
> You were absolutely correct! The completed date field is empty only for recurring tasks, it works OK for normal tasks. So I just attached some logic that merges date info from other APIs and it works fine now.
> 
> Thanks a lot for helping identify this issue!
> 
> The new version has already been released!

Amazing. Just tried and works perfectly. Thank you!
