### ISSUE TITLE
cannot fetch when using template code of "keyword segment"

### ISSUE THREAD

**Issue by KristineWatson** [Ledaryy/obsidian-todoist-completed-tasks#26]
copy the same code but it still doesn't work , did i missed anything?
![图片](https://user-images.githubusercontent.com/92555979/218432596-81843448-1ba0-4296-84ac-e438144dc834.png)

**Comment by Ledaryy** [comment]
Hey @KristineWatson 
Sorry for a bit late response. I just tried the same at my local setup and it seems to be working fine.
If this issue still persists, could you please provide me with more information? Such as the complete text that you're using here.
And your plugin version/operating system/obsidian version.
Thanks!

**Comment by Ledaryy** [comment]
Closing issue because it was inactive for a couple of months
