### ISSUE TITLE
(feat req) - add todoist link option to postfix

### ISSUE THREAD

**Issue by erauner12** [Ledaryy/obsidian-todoist-completed-tasks#32]
something like `{todoist_url}`.

It would be ideal if this url were in hyperlink format.

ex:
`[task](https://todoist.com/app/task/<id>)`

Let me know what you think

**Comment by geoelectric** [comment]
I'd like this functionality as well. Having it paste in as a full hyperlink might be hard to juggle with the default behavior of bringing in the title text though.

OTOH, a prefix of `- [x] [` and a postfix of `](todoist_url)` (inserted as a raw URL) would give me exactly what I want: a clickable link back to the original task, with an Obsidian checkbox marked complete.

**Comment by Ledaryy** [comment]
Hi @erauner12 @geoelectric 
Thanks for the suggestions!
This issue seems like a duplicate of https://github.com/Ledaryy/obsidian-todoist-completed-tasks/issues/24
so, I'll close this one.
